// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

/**
 * Content for Client documents
 */
interface ClientsDocumentData {
  /**
   * image field in *Client*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Client document from Prismic
 *
 * - **API ID**: `clients`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ClientsDocumentData>,
    'clients',
    Lang
  >

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    'navigation',
    Lang
  >

/**
 * Item in *Page → SEO*
 */
export interface PageDocumentDataSeoItem {
  /**
   * title field in *Page → SEO*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.seo[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *Page → SEO*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.seo[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField

  /**
   * Featured image field in *Page → SEO*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: page.seo[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField
}

type PageDocumentDataSlicesSlice =
  | _404Slice
  | HeroSlice
  | ImageSlice
  | TextWithFeaturesSlice
  | TextWithImageSlice
  | LogoSlice
  | MainLogoSlice
  | LanguageSelectorSlice
  | AboutTextWithButtonSlice
  | FloatingImageSlice
  | MansorySlice
  | LogoMarqueeSlice
  | FooterSlice
  | TopBarSlice
  | FloatingImagesSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for the page
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * SEO field in *Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page.seo[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  seo: prismic.GroupField<Simplify<PageDocumentDataSeoItem>>

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>

type PortfolioDocumentDataSlicesSlice = never

/**
 * Content for Portfolio documents
 */
interface PortfolioDocumentData {
  /**
   * `slices` field in *Portfolio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfolioDocumentDataSlicesSlice>
}

/**
 * Portfolio document from Prismic
 *
 * - **API ID**: `portfolio`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PortfolioDocumentData>,
    'portfolio',
    Lang
  >

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField

  /**
   * favicon field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.favicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  favicon: prismic.ImageField<never>
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    'settings',
    Lang
  >

export type AllDocumentTypes =
  | ClientsDocument
  | NavigationDocument
  | PageDocument
  | PortfolioDocument
  | SettingsDocument

/**
 * Primary content in *PageNotFound → Default → Primary*
 */
export interface _404SliceDefaultPrimary {
  /**
   * 404 Image field in *PageNotFound → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: 404.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>

  /**
   * Page Not Found field in *PageNotFound → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: 404.default.primary.page_not_found
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  page_not_found: prismic.ImageField<never>
}

/**
 * Default variation for PageNotFound Slice
 *
 * - **API ID**: `default`
 * - **Description**: 404
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type _404SliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<_404SliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *PageNotFound*
 */
type _404SliceVariation = _404SliceDefault

/**
 * PageNotFound Shared Slice
 *
 * - **API ID**: `404`
 * - **Description**: 404
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type _404Slice = prismic.SharedSlice<'404', _404SliceVariation>

/**
 * Primary content in *AboutTextWithButton → Default → Primary*
 */
export interface AboutTextWithButtonSliceDefaultPrimary {
  /**
   * About field in *AboutTextWithButton → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_text_with_button.default.primary.about
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about: prismic.RichTextField

  /**
   * Button name field in *AboutTextWithButton → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_text_with_button.default.primary.button_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_name: prismic.KeyTextField

  /**
   * Button link field in *AboutTextWithButton → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_text_with_button.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Floating image field in *AboutTextWithButton → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_text_with_button.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for AboutTextWithButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: AboutTextWithButton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTextWithButtonSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<AboutTextWithButtonSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *AboutTextWithButton*
 */
type AboutTextWithButtonSliceVariation = AboutTextWithButtonSliceDefault

/**
 * AboutTextWithButton Shared Slice
 *
 * - **API ID**: `about_text_with_button`
 * - **Description**: AboutTextWithButton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTextWithButtonSlice = prismic.SharedSlice<
  'about_text_with_button',
  AboutTextWithButtonSliceVariation
>

/**
 * Primary content in *FloatingImage → Default → Primary*
 */
export interface FloatingImageSliceDefaultPrimary {
  /**
   * Image field in *FloatingImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: floating_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for FloatingImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: FloatingImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FloatingImageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FloatingImageSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FloatingImage*
 */
type FloatingImageSliceVariation = FloatingImageSliceDefault

/**
 * FloatingImage Shared Slice
 *
 * - **API ID**: `floating_image`
 * - **Description**: FloatingImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FloatingImageSlice = prismic.SharedSlice<
  'floating_image',
  FloatingImageSliceVariation
>

/**
 * Primary content in *FloatingImages → Items*
 */
export interface FloatingImagesSliceDefaultItem {
  /**
   * image field in *FloatingImages → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: floating_images.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for FloatingImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: FloatingImages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FloatingImagesSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<FloatingImagesSliceDefaultItem>
>

/**
 * Slice variation for *FloatingImages*
 */
type FloatingImagesSliceVariation = FloatingImagesSliceDefault

/**
 * FloatingImages Shared Slice
 *
 * - **API ID**: `floating_images`
 * - **Description**: FloatingImages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FloatingImagesSlice = prismic.SharedSlice<
  'floating_images',
  FloatingImagesSliceVariation
>

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<'footer', FooterSliceVariation>

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Introductory text for the page
   * - **API ID Path**: hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *Hero → With Button → Primary*
 */
export interface HeroSliceWithButtonPrimary {
  /**
   * Text field in *Hero → With Button → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Introductory text for the page
   * - **API ID Path**: hero.withButton.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Button Text field in *Hero → With Button → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withButton.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField

  /**
   * Button Link field in *Hero → With Button → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withButton.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField

  /**
   * Image field in *Hero → With Button → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withButton.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * With Button variation for Hero Slice
 *
 * - **API ID**: `withButton`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceWithButton = prismic.SharedSliceVariation<
  'withButton',
  Simplify<HeroSliceWithButtonPrimary>,
  never
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceWithButton

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>

/**
 * Primary content in *Image → White → Primary*
 */
export interface ImageSliceWhitePrimary {
  /**
   * Image field in *Image → White → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.white.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * With Accent field in *Image → White → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image.white.primary.withAccent
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  withAccent: prismic.BooleanField
}

/**
 * White variation for Image Slice
 *
 * - **API ID**: `white`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceWhite = prismic.SharedSliceVariation<
  'white',
  Simplify<ImageSliceWhitePrimary>,
  never
>

/**
 * Primary content in *Image → Light Slate → Primary*
 */
export interface ImageSliceLightSlatePrimary {
  /**
   * Image field in *Image → Light Slate → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.lightSlate.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * With Accent field in *Image → Light Slate → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image.lightSlate.primary.withAccent
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  withAccent: prismic.BooleanField
}

/**
 * Light Slate variation for Image Slice
 *
 * - **API ID**: `lightSlate`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceLightSlate = prismic.SharedSliceVariation<
  'lightSlate',
  Simplify<ImageSliceLightSlatePrimary>,
  never
>

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceWhite | ImageSliceLightSlate

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<'image', ImageSliceVariation>

/**
 * Primary content in *LanguageSelector → Default → Primary*
 */
export interface LanguageSelectorSliceDefaultPrimary {
  /**
   * image field in *LanguageSelector → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: language_selector.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for LanguageSelector Slice
 *
 * - **API ID**: `default`
 * - **Description**: LanguageSelector
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LanguageSelectorSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<LanguageSelectorSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *LanguageSelector*
 */
type LanguageSelectorSliceVariation = LanguageSelectorSliceDefault

/**
 * LanguageSelector Shared Slice
 *
 * - **API ID**: `language_selector`
 * - **Description**: LanguageSelector
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LanguageSelectorSlice = prismic.SharedSlice<
  'language_selector',
  LanguageSelectorSliceVariation
>

/**
 * Primary content in *Logo → Default → Primary*
 */
export interface LogoSliceDefaultPrimary {
  /**
   * image field in *Logo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for Logo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Logo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<LogoSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Logo*
 */
type LogoSliceVariation = LogoSliceDefault

/**
 * Logo Shared Slice
 *
 * - **API ID**: `logo`
 * - **Description**: Logo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSlice = prismic.SharedSlice<'logo', LogoSliceVariation>

/**
 * Primary content in *LogoMarquee → Default → Primary*
 */
export interface LogoMarqueeSliceDefaultPrimary {
  /**
   * title field in *LogoMarquee → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_marquee.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Marquee Speed field in *LogoMarquee → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_marquee.default.primary.speed
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  speed: prismic.KeyTextField
}

/**
 * Primary content in *LogoMarquee → Items*
 */
export interface LogoMarqueeSliceDefaultItem {
  /**
   * image field in *LogoMarquee → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_marquee.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * link field in *LogoMarquee → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_marquee.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Default variation for LogoMarquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: LogoMarquee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoMarqueeSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<LogoMarqueeSliceDefaultPrimary>,
  Simplify<LogoMarqueeSliceDefaultItem>
>

/**
 * Slice variation for *LogoMarquee*
 */
type LogoMarqueeSliceVariation = LogoMarqueeSliceDefault

/**
 * LogoMarquee Shared Slice
 *
 * - **API ID**: `logo_marquee`
 * - **Description**: LogoMarquee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoMarqueeSlice = prismic.SharedSlice<
  'logo_marquee',
  LogoMarqueeSliceVariation
>

/**
 * Primary content in *MainMenu → Default → Primary*
 */
export interface MainLogoSliceDefaultPrimary {
  /**
   * logo field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_logo.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * menu image field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_logo.default.primary.menu
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  menu: prismic.ImageField<never>

  /**
   * background image field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_logo.default.primary.bgImg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgImg: prismic.ImageField<never>

  /**
   * Logo Bg field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_logo.default.primary.logo_bg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_bg: prismic.ImageField<never>

  /**
   * Work Menu Bg field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_logo.default.primary.work_menu_bg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  work_menu_bg: prismic.ImageField<never>
}

/**
 * Default variation for MainMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: MainLogo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainLogoSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MainLogoSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *MainMenu → Gallery → Primary*
 */
export interface MainLogoSliceGalleryPrimary {
  /**
   * logo field in *MainMenu → Gallery → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_logo.gallery.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * menu image field in *MainMenu → Gallery → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_logo.gallery.primary.menu
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  menu: prismic.ImageField<never>

  /**
   * Work Menu Bg field in *MainMenu → Gallery → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_logo.gallery.primary.work_menu_bg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  work_menu_bg: prismic.ImageField<never>
}

/**
 * Gallery variation for MainMenu Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: MainLogo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainLogoSliceGallery = prismic.SharedSliceVariation<
  'gallery',
  Simplify<MainLogoSliceGalleryPrimary>,
  never
>

/**
 * Slice variation for *MainMenu*
 */
type MainLogoSliceVariation = MainLogoSliceDefault | MainLogoSliceGallery

/**
 * MainMenu Shared Slice
 *
 * - **API ID**: `main_logo`
 * - **Description**: MainLogo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainLogoSlice = prismic.SharedSlice<
  'main_logo',
  MainLogoSliceVariation
>

/**
 * Primary content in *Mansory → Default → Primary*
 */
export interface MansorySliceDefaultPrimary {
  /**
   * One Column? field in *Mansory → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: mansory.default.primary.oneColumn
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  oneColumn: prismic.BooleanField

  /**
   * No of Columns field in *Mansory → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: mansory.default.primary.no_of_columns
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  no_of_columns: prismic.NumberField
}

/**
 * Primary content in *Mansory → Items*
 */
export interface MansorySliceDefaultItem {
  /**
   * Is Clickable field in *Mansory → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: mansory.items[].is_clickable
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_clickable: prismic.BooleanField

  /**
   * Imagem Destacada field in *Mansory → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mansory.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Media field in *Mansory → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: mansory.items[].media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  media: prismic.LinkToMediaField

  /**
   * Imagem MouseOver field in *Mansory → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mansory.items[].image_hover
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_hover: prismic.ImageField<never>

  /**
   * Descrição field in *Mansory → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mansory.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField
}

/**
 * Default variation for Mansory Slice
 *
 * - **API ID**: `default`
 * - **Description**: Mansory
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MansorySliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MansorySliceDefaultPrimary>,
  Simplify<MansorySliceDefaultItem>
>

/**
 * Primary content in *Mansory → Mansory Vertical → Primary*
 */
export interface MansorySliceMansoryVerticalPrimary {
  /**
   * No of Columns field in *Mansory → Mansory Vertical → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: mansory.mansoryVertical.primary.no_of_columns
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  no_of_columns: prismic.NumberField
}

/**
 * Primary content in *Mansory → Items*
 */
export interface MansorySliceMansoryVerticalItem {
  /**
   * Is Clickable field in *Mansory → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: mansory.items[].is_clickable
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_clickable: prismic.BooleanField

  /**
   * Imagem Destacada field in *Mansory → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mansory.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Media field in *Mansory → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: mansory.items[].media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  media: prismic.LinkToMediaField

  /**
   * Imagem MouseOver field in *Mansory → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mansory.items[].image_hover
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_hover: prismic.ImageField<never>

  /**
   * Descrição field in *Mansory → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mansory.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField
}

/**
 * Mansory Vertical variation for Mansory Slice
 *
 * - **API ID**: `mansoryVertical`
 * - **Description**: Mansory
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MansorySliceMansoryVertical = prismic.SharedSliceVariation<
  'mansoryVertical',
  Simplify<MansorySliceMansoryVerticalPrimary>,
  Simplify<MansorySliceMansoryVerticalItem>
>

/**
 * Slice variation for *Mansory*
 */
type MansorySliceVariation = MansorySliceDefault | MansorySliceMansoryVertical

/**
 * Mansory Shared Slice
 *
 * - **API ID**: `mansory`
 * - **Description**: Mansory
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MansorySlice = prismic.SharedSlice<'mansory', MansorySliceVariation>

/**
 * Primary content in *TextWithFeatures → Default → Primary*
 */
export interface TextWithFeaturesSliceDefaultPrimary {
  /**
   * Icon field in *TextWithFeatures → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_features.default.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>

  /**
   * Text field in *TextWithFeatures → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Primary text with rich formatting
   * - **API ID Path**: text_with_features.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * Primary content in *TextWithFeatures → Items*
 */
export interface TextWithFeaturesSliceDefaultItem {
  /**
   * Feature Description field in *TextWithFeatures → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description of a feature
   * - **API ID Path**: text_with_features.items[].featureDescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featureDescription: prismic.RichTextField
}

/**
 * Default variation for TextWithFeatures Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithFeatures
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithFeaturesSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TextWithFeaturesSliceDefaultPrimary>,
  Simplify<TextWithFeaturesSliceDefaultItem>
>

/**
 * Slice variation for *TextWithFeatures*
 */
type TextWithFeaturesSliceVariation = TextWithFeaturesSliceDefault

/**
 * TextWithFeatures Shared Slice
 *
 * - **API ID**: `text_with_features`
 * - **Description**: TextWithFeatures
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithFeaturesSlice = prismic.SharedSlice<
  'text_with_features',
  TextWithFeaturesSliceVariation
>

/**
 * Primary content in *TextWithImage → Default → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
  /**
   * Text field in *TextWithImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text displayed next to image
   * - **API ID Path**: text_with_image.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Image field in *TextWithImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TextWithImageSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *TextWithImage*
 */
type TextWithImageSliceVariation = TextWithImageSliceDefault

/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
  'text_with_image',
  TextWithImageSliceVariation
>

/**
 * Primary content in *TopBar → Default → Primary*
 */
export interface TopBarSliceDefaultPrimary {
  /**
   * image field in *TopBar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: top_bar.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Is Clickable field in *TopBar → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: top_bar.default.primary.is_clickable
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_clickable: prismic.BooleanField
}

/**
 * Default variation for TopBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: TopBar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopBarSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TopBarSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *TopBar*
 */
type TopBarSliceVariation = TopBarSliceDefault

/**
 * TopBar Shared Slice
 *
 * - **API ID**: `top_bar`
 * - **Description**: TopBar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopBarSlice = prismic.SharedSlice<'top_bar', TopBarSliceVariation>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>
  }

  namespace Content {
    export type {
      ClientsDocument,
      ClientsDocumentData,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSeoItem,
      PageDocumentDataSlicesSlice,
      PortfolioDocument,
      PortfolioDocumentData,
      PortfolioDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      _404Slice,
      _404SliceDefaultPrimary,
      _404SliceVariation,
      _404SliceDefault,
      AboutTextWithButtonSlice,
      AboutTextWithButtonSliceDefaultPrimary,
      AboutTextWithButtonSliceVariation,
      AboutTextWithButtonSliceDefault,
      FloatingImageSlice,
      FloatingImageSliceDefaultPrimary,
      FloatingImageSliceVariation,
      FloatingImageSliceDefault,
      FloatingImagesSlice,
      FloatingImagesSliceDefaultItem,
      FloatingImagesSliceVariation,
      FloatingImagesSliceDefault,
      FooterSlice,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceWithButtonPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceWithButton,
      ImageSlice,
      ImageSliceWhitePrimary,
      ImageSliceLightSlatePrimary,
      ImageSliceVariation,
      ImageSliceWhite,
      ImageSliceLightSlate,
      LanguageSelectorSlice,
      LanguageSelectorSliceDefaultPrimary,
      LanguageSelectorSliceVariation,
      LanguageSelectorSliceDefault,
      LogoSlice,
      LogoSliceDefaultPrimary,
      LogoSliceVariation,
      LogoSliceDefault,
      LogoMarqueeSlice,
      LogoMarqueeSliceDefaultPrimary,
      LogoMarqueeSliceDefaultItem,
      LogoMarqueeSliceVariation,
      LogoMarqueeSliceDefault,
      MainLogoSlice,
      MainLogoSliceDefaultPrimary,
      MainLogoSliceGalleryPrimary,
      MainLogoSliceVariation,
      MainLogoSliceDefault,
      MainLogoSliceGallery,
      MansorySlice,
      MansorySliceDefaultPrimary,
      MansorySliceDefaultItem,
      MansorySliceMansoryVerticalPrimary,
      MansorySliceMansoryVerticalItem,
      MansorySliceVariation,
      MansorySliceDefault,
      MansorySliceMansoryVertical,
      TextWithFeaturesSlice,
      TextWithFeaturesSliceDefaultPrimary,
      TextWithFeaturesSliceDefaultItem,
      TextWithFeaturesSliceVariation,
      TextWithFeaturesSliceDefault,
      TextWithImageSlice,
      TextWithImageSliceDefaultPrimary,
      TextWithImageSliceVariation,
      TextWithImageSliceDefault,
      TopBarSlice,
      TopBarSliceDefaultPrimary,
      TopBarSliceVariation,
      TopBarSliceDefault,
    }
  }
}
